---
name: Build and Test 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  BUILD_DIR: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} . -B./${{env.BUILD_DIR}}

      - name: Build
        working-directory: ${{env.BUILD_DIR}}
        run: make

      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ./unit_tests 
